# -*- coding: utf-8 -*-
"""try 2 build stocks app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13SR90pZr4vOfVNx5OwbCMYoJ9U_oIN-0

# **Basic info of stock**
"""

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import os # Import os module for path operations
from typing import Union, List # Import Union and List for type hinting

def scrape_finviz_country_data(country_code: str, output_dir: str = '.', max_pages: int = 20, ticker_symbol: Union[str, List[str], None] = None) -> pd.DataFrame:
    """
    Scrapes stock data from Finviz for a specified country and a given number of pages,
    saves it to a CSV, and returns a DataFrame.

    Args:
        country_code (str): The country code to filter Finviz data (e.g., 'USA').
        output_dir (str): The directory where the CSV file will be saved. Defaults to current directory.
        max_pages (int): The maximum number of pages to scrape.
        ticker_symbol (Union[str, List[str], None], optional): A specific stock ticker symbol or list of symbols to filter the results by. Defaults to None.

    Returns:
        pd.DataFrame: A DataFrame containing the scraped stock data.
    """
    base_url = "https://finviz.com/screener.ashx"
    headers_request = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    all_scraped_data = []
    column_headers = []

    # Set base_params to filter by the country_code
    base_params = {
        'c': country_code
    }

    # Logic to process ticker_symbol for server-side filtering
    tickers_to_filter = []
    if ticker_symbol is not None:
        if isinstance(ticker_symbol, str):
            tickers_to_filter.append(ticker_symbol.upper())
        elif isinstance(ticker_symbol, list):
            for ticker in ticker_symbol:
                if isinstance(ticker, str):
                    tickers_to_filter.append(ticker.upper())

    if tickers_to_filter:
        ticker_filter_string = ','.join(tickers_to_filter)
        base_params['t'] = ticker_filter_string

    for page_num in range(1, max_pages + 1):
        offset = (page_num - 1) * 20 + 1
        current_params = base_params.copy()
        current_params['p'] = offset

        print(f"Scraping page {page_num} of {max_pages} for {country_code} with offset {offset}...")

        try:
            response = requests.get(base_url, params=current_params, headers=headers_request)
            response.raise_for_status() # Raise an exception for bad status codes
            time.sleep(5) # Add a delay to avoid being blocked
        except requests.exceptions.RequestException as e:
            print(f"Request failed for page {page_num}: {e}")
            break # Stop if a request fails

        soup = BeautifulSoup(response.text, 'html.parser')

        table = soup.find('table', class_='screener_table')
        if not table:
            table = soup.find('table', {'width': '100%', 'cellpadding': '3', 'cellspacing': '0'}) # Fallback

        if not table:
            print(f"Could not find the screener results table on page {page_num}. Ending scraping.")
            break
        else:
            # Extract column headers only once from the first page
            if not column_headers:
                header_row = table.find('tr')
                if header_row:
                    column_headers = [th.get_text(strip=True) for th in header_row.find_all('th')]
                else:
                    print(f"Could not find header row on page {page_num}.")
                    break

            # Extract data rows
            page_data = []
            all_rows = table.find_all('tr')

            # Determine the starting index for data rows, skipping the header if found
            start_row_index = 0
            if column_headers and all_rows and all_rows[0].find('th'):
                start_row_index = 1

            for row in all_rows[start_row_index:]:
                cells = [td.get_text(strip=True) for td in row.find_all('td')]
                # Ensure cells are not empty and match header length if headers exist
                if cells and (not column_headers or len(cells) == len(column_headers)):
                    page_data.append(cells)

            if page_data:
                all_scraped_data.extend(page_data)
            else:
                print(f"No new data rows found on page {page_num}. Ending scraping.")
                break

    if all_scraped_data and column_headers:
        df = pd.DataFrame(all_scraped_data, columns=column_headers)
    else:
        print("No data or headers were successfully scraped.")
        df = pd.DataFrame(columns=column_headers if column_headers else [])

    # The original client-side filtering logic for ticker_symbol is now redundant if server-side filtering is used.
    # However, for robustness (e.g., if Finviz changes its URL parameter or for multiple tickers not fully supported by 't'),
    # keeping it as a fallback or for additional filtering is an option. For this subtask, we assume 't' is sufficient.
    # The previous filtering was: df_filtered_by_ticker = df[df['Ticker'].str.upper() == ticker_symbol.upper()].copy()
    # Since the 't' parameter handles this server-side, this block is removed.

    # Save DataFrame to CSV
    if not df.empty:
        os.makedirs(output_dir, exist_ok=True)
        # Adjust file name if specific tickers were filtered via the 't' parameter
        if tickers_to_filter:
            file_name = f"finviz_{country_code}_stocks.csv"
        else:
            file_name = f"finviz_{country_code}_stocks.csv"
        file_path = os.path.join(output_dir, file_name)
        df.to_csv(file_path, index=False)
        print(f"DataFrame saved to: {os.path.abspath(file_path)}")
    else:
        print(f"No data to save for {country_code} with specified tickers.")

    return df

print("scrape_finviz_country_data function defined and updated to save CSV, filter by ticker server-side, and use type hints.")

import os

# Call the function with 'USA' and max_pages=2
my_finviz_df = scrape_finviz_country_data(country_code='USA', ticker_symbol=['AAPL'], max_pages=1)

# Display the head of the returned DataFrame
print("\nHead of the scraped USA data DataFrame:")
display(my_finviz_df.head())

# @title
import pandas as pd
import os

global unique_tickers

if 'my_finviz_df' in locals() and not my_finviz_df.empty and 'Ticker' in my_finviz_df.columns:
    unique_tickers = my_finviz_df['Ticker'].unique().tolist()
    print(f"Global variable 'unique_tickers' created with {len(unique_tickers)} items from my_finviz_df.")
    print(f"First 5 tickers: {unique_tickers[:5]}")
else:
    print("my_finviz_df is not directly available or lacks 'Ticker' column. Attempting to load from CSV...")
    csv_file_path = '/content/finviz_USA_stocks.csv'
    if os.path.exists(csv_file_path):
        try:
            temp_df = pd.read_csv(csv_file_path)
            if 'Ticker' in temp_df.columns:
                unique_tickers = temp_df['Ticker'].unique().tolist()
                print(f"Global variable 'unique_tickers' loaded from CSV with {len(unique_tickers)} items.")
                print(f"First 5 tickers: {unique_tickers[:5]}")
            else:
                unique_tickers = []
                print("Error: 'Ticker' column not found in finviz_USA_stocks.csv. 'unique_tickers' is empty.")
        except Exception as e:
            unique_tickers = []
            print(f"Error loading finviz_USA_stocks.csv: {e}. 'unique_tickers' is empty.")
    else:
        unique_tickers = []
        print(f"Error: '{csv_file_path}' not found. 'unique_tickers' is empty.")

if not unique_tickers:
    print("Warning: 'unique_tickers' list is empty. Subsequent operations requiring this list may fail.")

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re # Added for clean_value_yahoo function

def clean_value_yahoo(value_str):
    if isinstance(value_str, (int, float)):
        return value_str
    if not isinstance(value_str, str):
        return None

    value_str = value_str.strip().replace(',', '').replace('$', '')

    if value_str.lower() in ('none', '-', 'inf', 'n/a'):
        return None

    multiplier = 1
    if value_str.endswith('B'):
        multiplier = 1e9
        value_str = value_str[:-1]
    elif value_str.endswith('M'):
        multiplier = 1e6
        value_str = value_str[:-1]
    elif value_str.endswith('K'):
        multiplier = 1e3
        value_str = value_str[:-1]
    elif value_str.endswith('%'):
        multiplier = 0.01
        value_str = value_str[:-1]

    cleaned_text = re.sub(r'[^-.0-9]', '', value_str)

    if cleaned_text and cleaned_text != '.' and cleaned_text.count('.') <= 1 and cleaned_text != '-':
        try:
            return float(cleaned_text) * multiplier
        except ValueError:
            return None
    return None

def scrape_dataroma_investor_data(ticker):
    """
    Scrapes super investor holdings and insider trading summary data for a given ticker
    from Dataroma.com.

    Args:
        ticker (str): The stock ticker symbol (e.g., 'AAPL').

    Returns:
        tuple: A tuple containing two pandas DataFrames:
               - super_investor_df (pd.DataFrame): Data about super investor holdings for the ticker.
               - insider_trades_df (pd.DataFrame): Data about insider trades summary for the ticker.
               Returns empty DataFrames if data cannot be retrieved or parsed.
    """
    dataroma_base_url = "https://www.dataroma.com/m/stock.php"
    search_url = f"{dataroma_base_url}?sym={ticker}"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }

    super_investor_data = []
    insider_trades_data = []
    super_investor_columns = []
    insider_trades_columns = []

    try:
        response = requests.get(search_url, headers=headers)
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
        time.sleep(3) # Be polite and add a delay

        soup = BeautifulSoup(response.text, 'html.parser')

        # --- Extract Super Investor Holdings from table with id="grid" ---
        super_investor_table = soup.find('table', id='grid')
        if super_investor_table:
            # print(f"[DEBUG] Found Superinvestor (id='grid') table for {ticker}.")
            header_row = super_investor_table.find('thead').find_all('tr')[0]
            super_investor_columns = [th.get_text(strip=True) for th in header_row.find_all(['th', 'td'])]
            if super_investor_columns and super_investor_columns[0] == '':
                super_investor_columns = super_investor_columns[1:]

            data_rows = super_investor_table.find('tbody').find_all('tr')
            for row in data_rows:
                cells = [td.get_text(strip=True) for td in row.find_all('td')]
                if cells and cells[0] == '\u2261':
                    cells = cells[1:]

                if cells and len(cells) == len(super_investor_columns):
                    super_investor_data.append(cells)

        # --- Extract Insider Buying/Selling Summary from table with id="ins_sum" ---
        insider_trades_table = soup.find('table', id='ins_sum')
        if insider_trades_table:
            # print(f"[DEBUG] Found Insider Trades (id='ins_sum') table for {ticker}.")
            all_theads_in_ins_sum = insider_trades_table.find_all('thead')
            if len(all_theads_in_ins_sum) >= 2:
                header_row = all_theads_in_ins_sum[1].find('tr')
                if header_row:
                    insider_trades_columns = [th.get_text(strip=True) for th in header_row.find_all(['th', 'td'])]

                data_rows = insider_trades_table.find('tbody').find_all('tr')
                for row in data_rows:
                    cells = [td.get_text(strip=True) for td in row.find_all('td')]
                    if cells and len(cells) == len(insider_trades_columns):
                        insider_trades_data.append(cells)

    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for {ticker} from Dataroma: {e}")
    except Exception as e:
        print(f"An unexpected error occurred while parsing data for {ticker}: {e}")

    # Create DataFrames. Ensure columns are set only if data exists and matches column count.
    super_investor_df = pd.DataFrame(super_investor_data, columns=super_investor_columns if super_investor_data else [])
    insider_trades_df = pd.DataFrame(insider_trades_data, columns=insider_trades_columns if insider_trades_data else [])

    if not super_investor_df.empty:
        super_investor_df['Ticker'] = ticker
    if not insider_trades_df.empty:
        insider_trades_df['Ticker'] = ticker

    return super_investor_df, insider_trades_df

print("scrape_dataroma_investor_data function defined.")
print("clean_value_yahoo function defined.")

"""# **datarama super and institutional investor data**"""

# @title
all_super_investor_data = []
all_insider_trades_data = []

if unique_tickers:
    print(f"Starting to scrape Dataroma for {len(unique_tickers)} unique tickers...")
    for i, ticker in enumerate(unique_tickers):
        print(f"Processing ticker {i+1}/{len(unique_tickers)}: {ticker}")
        super_investor_df, insider_trades_df = scrape_dataroma_investor_data(ticker)

        # Apply clean_value_yahoo to super_investor_df columns
        if not super_investor_df.empty:
            for col in ['% of portfolio', 'Shares', 'Value']:
                if col in super_investor_df.columns:
                    super_investor_df[col] = super_investor_df[col].apply(clean_value_yahoo)
            all_super_investor_data.append(super_investor_df)

        # Apply clean_value_yahoo to insider_trades_df columns and rename first column
        if not insider_trades_df.empty:
            # Rename the first column to 'Transaction Type'
            if '' in insider_trades_df.columns:
                insider_trades_df.rename(columns={'': 'Transaction Type'}, inplace=True)
            elif insider_trades_df.columns[0] != 'Transaction Type': # Fallback to direct renaming of the first column
                insider_trades_df.columns.values[0] = 'Transaction Type'

            if 'Total' in insider_trades_df.columns:
                insider_trades_df['Total'] = insider_trades_df['Total'].apply(clean_value_yahoo)
            all_insider_trades_data.append(insider_trades_df)

    # Consolidate all data into final DataFrames
    final_super_investor_df = pd.concat(all_super_investor_data, ignore_index=True) if all_super_investor_data else pd.DataFrame()
    final_insider_trades_df = pd.concat(all_insider_trades_data, ignore_index=True) if all_insider_trades_data else pd.DataFrame()

    print("\n--- Consolidated Super Investor Data ---")
    if not final_super_investor_df.empty:
        display(final_super_investor_df.sort_values(by=['Ticker'], ascending=True).head(15))
        print(f"Total Super Investor records across all tickers: {len(final_super_investor_df)}")
        print(f"Columns: {final_super_investor_df.columns.tolist()}")
    else:
        print("No super investor data found for any ticker.")

    print("\n--- Consolidated Insider Trades Data ---")
    if not final_insider_trades_df.empty:
        display(final_insider_trades_df.sort_values(by=['Ticker', 'Total'], ascending=[True, False]).head(15))
        print(f"Total Insider Trades records across all tickers: {len(final_insider_trades_df)}")
        print(f"Columns: {final_insider_trades_df.columns.tolist()}")

    else:
        print("No insider trades data found for any ticker.")
else:
    print("No unique tickers available to scrape Dataroma.")

"""# **Yahoo insider activity**"""

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re # Added for clean_value_yahoo function

def clean_value_yahoo(value_str):
    if isinstance(value_str, (int, float)):
        return value_str
    if not isinstance(value_str, str):
        return None

    value_str = value_str.strip().replace(',', '').replace('$', '')

    if value_str.lower() in ('none', '-', 'inf', 'n/a'):
        return None

    multiplier = 1
    if value_str.endswith('B'):
        multiplier = 1e9
        value_str = value_str[:-1]
    elif value_str.endswith('M'):
        multiplier = 1e6
        value_str = value_str[:-1]
    elif value_str.endswith('K'):
        multiplier = 1e3
        value_str = value_str[:-1]
    elif value_str.endswith('%'):
        multiplier = 0.01
        value_str = value_str[:-1]

    cleaned_text = re.sub(r'[^-.0-9]', '', value_str)

    if cleaned_text and cleaned_text != '.' and cleaned_text.count('.') <= 1 and cleaned_text != '-':
        try:
            return float(cleaned_text) * multiplier
        except ValueError:
            return None
    return None

def get_yahoo_finance_page_with_session(ticker, url_path):
    """
    Attempts to fetch a Yahoo Finance page, handling the consent page using a persistent session.
    Returns a BeautifulSoup object of the page if successful, None otherwise.
    """
    session = requests.Session() # Initialize a session to persist cookies
    base_url = "https://finance.yahoo.com/quote/"
    target_url = f"{base_url}{ticker}{url_path}"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1'
    }

    print(f"Attempting initial GET request to: {target_url} using session...")
    try:
        response_initial = session.get(target_url, headers=headers, allow_redirects=True)
        response_initial.raise_for_status()
        time.sleep(3)

        if "consent" in response_initial.url.lower() or "consent.cmp.oath.com" in response_initial.url.lower() or "consent.yahoo.com" in response_initial.url.lower() or "We need your consent" in response_initial.text:
            print(f"Detected Yahoo consent page at: {response_initial.url}")

            soup_consent = BeautifulSoup(response_initial.text, 'html.parser')
            consent_form = soup_consent.find('form', {'action': True, 'method': 'post'})
            if not consent_form:
                print("Could not find the consent form on the page. Cannot bypass.")
                return None

            form_data = {}
            for input_tag in consent_form.find_all('input', {'type': 'hidden'}):
                name = input_tag.get('name')
                value = input_tag.get('value')
                if name and value:
                    form_data[name] = value

            post_url = consent_form.get('action')
            if not post_url.startswith('http'):
                from urllib.parse import urljoin
                post_url = urljoin(response_initial.url, post_url)

            form_data['agree'] = 'agree'
            form_data['.submit'] = 'agree'
            headers['Referer'] = response_initial.url

            print(f"Submitting consent POST request to: {post_url} using session...")
            response_post = session.post(post_url, data=form_data, headers=headers, allow_redirects=True)
            response_post.raise_for_status()
            time.sleep(5)

            print(f"Consent POST successful. Final URL after consent: {response_post.url}")
            return BeautifulSoup(response_post.text, 'html.parser')
        else:
            print(f"Successfully accessed target page: {response_initial.url}")
            return BeautifulSoup(response_initial.text, 'html.parser')

    except requests.exceptions.RequestException as e:
        print(f"Error during Yahoo Finance access for {ticker}: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred during Yahoo Finance access: {e}")
        return None

def _scrape_single_ticker_insider_transactions_data(ticker):
    """
    Helper function to scrape insider transactions data for a single ticker from Yahoo Finance.
    """
    soup = get_yahoo_finance_page_with_session(ticker, '/insider-transactions/')
    if not soup:
        return pd.DataFrame()

    target_table = soup.find('table', class_='yf-idy1mk')
    if not target_table:
        print(f"Could not find the insider transactions table (table.yf-idy1mk) for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from insider transactions table for {ticker}...")

    headers = []
    header_row = target_table.find('thead').find('tr')
    if header_row:
        headers = [th.get_text(strip=True) for th in header_row.find_all('th')]

    if not headers:
        print(f"Could not extract headers from the insider transactions table for {ticker}.")
        return pd.DataFrame()

    data = []
    for row in target_table.find('tbody').find_all('tr'):
        cells = [td.get_text(strip=True) for td in row.find_all('td')]
        if cells and len(cells) == len(headers):
            data.append(cells)

    if data:
        df = pd.DataFrame(data, columns=headers)
        df['Ticker'] = ticker

        # Apply clean_value_yahoo to relevant numerical columns
        for col in ['Shares', 'Value', 'Shares Total', 'Price']:
            if col in df.columns:
                df[col] = df[col].apply(clean_value_yahoo)

        return df
    else:
        print(f"No data rows found in the insider transactions table for {ticker}.")
        return pd.DataFrame(columns=headers + ['Ticker'])

def scrape_yahoo_finance_insider_transactions_data(ticker_symbols):
    """
    Scrapes insider transactions data for one or more ticker symbols from Yahoo Finance.

    Args:
        ticker_symbols (Union[str, List[str]]): A single stock ticker symbol or a list of symbols.

    Returns:
        pd.DataFrame: A consolidated DataFrame containing insider transactions data for all specified tickers.
                      Returns an empty DataFrame if no data is found for any ticker.
    """
    if isinstance(ticker_symbols, str):
        tickers_to_process = [ticker_symbols]
    elif isinstance(ticker_symbols, list):
        tickers_to_process = ticker_symbols
    else:
        print("Invalid input for ticker_symbols. Must be a string or a list of strings.")
        return pd.DataFrame()

    all_transactions_data = []
    print(f"Starting to scrape Yahoo Finance Insider Transactions for {len(tickers_to_process)} tickers...")

    for i, ticker in enumerate(tickers_to_process):
        print(f"Processing ticker {i+1}/{len(tickers_to_process)}: {ticker}")
        df = _scrape_single_ticker_insider_transactions_data(ticker)
        if not df.empty:
            all_transactions_data.append(df)
        time.sleep(1) # Be polite and add a small delay between tickers

    if all_transactions_data:
        consolidated_df = pd.concat(all_transactions_data, ignore_index=True)
        return consolidated_df
    else:
        print("No insider transactions data collected for any ticker.")
        return pd.DataFrame()

print("scrape_yahoo_finance_insider_transactions_data function refactored to accept list of tickers.")
print("clean_value_yahoo function defined.")

if unique_tickers:
    print(f"\nScraping insider transactions data for {len(unique_tickers)} tickers...")
    final_yahoo_insider_transactions_df = scrape_yahoo_finance_insider_transactions_data(unique_tickers)

    if not final_yahoo_insider_transactions_df.empty:
        print(f"\n--- Scraped Insider Transactions Data for {len(unique_tickers)} tickers ---")
        display(final_yahoo_insider_transactions_df.head())
        print(f"\nDataFrame Shape: {final_yahoo_insider_transactions_df.shape}")
    else:
        print("Failed to retrieve insider transactions data for any of the tickers.")
else:
    print("No unique tickers available to test Yahoo Finance insider transactions scraping.")

"""# **yahoo Institutional Holders**"""

# @title
def _scrape_single_ticker_shareholder_data(ticker):
    """
    Helper function to scrape detailed shareholder data for a single ticker from Yahoo Finance.
    """
    soup = get_yahoo_finance_page_with_session(ticker, '/holders/')
    if not soup:
        return pd.DataFrame()

    # The table class 'yf-idy1mk' is observed to contain the relevant data for both major holders and institutional holders.
    # For this task, we will extract the first table with this class.
    target_table = soup.find('table', class_='yf-idy1mk')
    if not target_table:
        print(f"Could not find the shareholder data table (table.yf-idy1mk) for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from shareholder table for {ticker}...")

    headers = []
    header_row = target_table.find('thead').find('tr')
    if header_row:
        headers = [th.get_text(strip=True) for th in header_row.find_all('th')]

    if not headers:
        print(f"Could not extract headers from the shareholder table for {ticker}.")
        return pd.DataFrame()

    data = []
    for row in target_table.find('tbody').find_all('tr'):
        cells = [td.get_text(strip=True) for td in row.find_all('td')]
        if cells and len(cells) == len(headers):
            data.append(cells)

    if data:
        df = pd.DataFrame(data, columns=headers)
        df['Ticker'] = ticker

        # Rename 'Holder' to 'Investor Name' for consistency if needed, or keep as is.
        # Assuming 'Holder' is the investor name column as per inspection.
        df.rename(columns={'Holder': 'Investor Name'}, inplace=True)

        # Apply clean_value_yahoo to relevant numerical columns
        for col in ['Shares', 'Value', '% Out']:
            if col in df.columns:
                df[col] = df[col].apply(clean_value_yahoo)

        return df
    else:
        print(f"No data rows found in the shareholder table for {ticker}.")
        return pd.DataFrame(columns=headers + ['Ticker'])

def scrape_yahoo_finance_shareholder_data(ticker_symbols):
    """
    Scrapes detailed shareholder data for one or more ticker symbols from Yahoo Finance.

    Args:
        ticker_symbols (Union[str, List[str]]): A single stock ticker symbol or a list of symbols.

    Returns:
        pd.DataFrame: A consolidated DataFrame containing shareholder data for all specified tickers.
                      Returns an empty DataFrame if no data is found for any ticker.
    """
    if isinstance(ticker_symbols, str):
        tickers_to_process = [ticker_symbols]
    elif isinstance(ticker_symbols, list):
        tickers_to_process = ticker_symbols
    else:
        print("Invalid input for ticker_symbols. Must be a string or a list of strings.")
        return pd.DataFrame()

    all_shareholder_data = []
    print(f"Starting to scrape Yahoo Finance Shareholder Data for {len(tickers_to_process)} tickers...")

    for i, ticker in enumerate(tickers_to_process):
        print(f"Processing ticker {i+1}/{len(tickers_to_process)}: {ticker}")
        df = _scrape_single_ticker_shareholder_data(ticker)
        if not df.empty:
            all_shareholder_data.append(df)
        time.sleep(1) # Be polite and add a small delay between tickers

    if all_shareholder_data:
        consolidated_df = pd.concat(all_shareholder_data, ignore_index=True)
        return consolidated_df
    else:
        print("No shareholder data collected for any ticker.")
        return pd.DataFrame()

print("scrape_yahoo_finance_shareholder_data function defined.")

if unique_tickers:
    print(f"\nScraping shareholder data for {len(unique_tickers)} tickers...")
    final_yahoo_holders_df = scrape_yahoo_finance_shareholder_data(unique_tickers)

    if not final_yahoo_holders_df.empty:
        print(f"\n--- Scraped Shareholder Data for {len(unique_tickers)} tickers ---")
        display(final_yahoo_holders_df.head())
        print(f"\nDataFrame Shape: {final_yahoo_holders_df.shape}")
        print(f"Columns: {final_yahoo_holders_df.columns.tolist()}")
    else:
        print("Failed to retrieve shareholder data for any of the tickers.")
else:
    print("No unique tickers available to test Yahoo Finance shareholder data scraping.")

"""# **Yahoo Cash Flow**"""

# @title
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re

def get_yahoo_finance_page_with_session(ticker, url_path):
    """
    Attempts to fetch a Yahoo Finance page, handling the consent page using a persistent session.
    Returns a BeautifulSoup object of the page if successful, None otherwise.
    """
    session = requests.Session() # Initialize a session to persist cookies
    base_url = "https://finance.yahoo.com/quote/"
    target_url = f"{base_url}{ticker}{url_path}"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1'
    }

    print(f"Attempting initial GET request to: {target_url} using session...")
    try:
        response_initial = session.get(target_url, headers=headers, allow_redirects=True)
        response_initial.raise_for_status()
        time.sleep(3)

        if "consent" in response_initial.url.lower() or "consent.cmp.oath.com" in response_initial.url.lower() or "consent.yahoo.com" in response_initial.url.lower() or "We need your consent" in response_initial.text:
            print(f"Detected Yahoo consent page at: {response_initial.url}")

            soup_consent = BeautifulSoup(response_initial.text, 'html.parser')
            consent_form = soup_consent.find('form', {'action': True, 'method': 'post'})
            if not consent_form:
                print("Could not find the consent form on the page. Cannot bypass.")
                return None

            form_data = {}
            for input_tag in consent_form.find_all('input', {'type': 'hidden'}):
                name = input_tag.get('name')
                value = input_tag.get('value')
                if name and value:
                    form_data[name] = value

            post_url = consent_form.get('action')
            if not post_url.startswith('http'):
                from urllib.parse import urljoin
                post_url = urljoin(response_initial.url, post_url)

            form_data['agree'] = 'agree'
            form_data['.submit'] = 'agree'
            headers['Referer'] = response_initial.url

            print(f"Submitting consent POST request to: {post_url} using session...")
            response_post = session.post(post_url, data=form_data, headers=headers, allow_redirects=True)
            response_post.raise_for_status()
            time.sleep(5)

            print(f"Consent POST successful. Final URL after consent: {response_post.url}")
            return BeautifulSoup(response_post.text, 'html.parser')
        else:
            print(f"Successfully accessed target page: {response_initial.url}")
            return BeautifulSoup(response_initial.text, 'html.parser')

    except requests.exceptions.RequestException as e:
        print(f"Error during Yahoo Finance access for {ticker}: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred during Yahoo Finance access: {e}")
        return None

def clean_value(value_str):
    """
    Cleans a string value by removing non-numeric characters (except for '-' and '.') and converts to float.
    Handles 'None', '-' or 'inf' values gracefully.
    """
    if isinstance(value_str, (int, float)):
        return value_str
    if not isinstance(value_str, str):
        return None

    value_str = value_str.strip().replace(',', '') # Remove commas
    if value_str.lower() in ('none', '-', 'inf', 'n/a'):
        return None

    # Handle 'T', 'B', 'M' suffixes
    multiplier = 1
    if value_str.endswith('T'):
        multiplier = 1e12
        value_str = value_str[:-1]
    elif value_str.endswith('B'):
        multiplier = 1e9
        value_str = value_str[:-1]
    elif value_str.endswith('M'):
        multiplier = 1e6
        value_str = value_str[:-1]

    # Remove any remaining non-numeric chars except for '.' and '-'
    cleaned_text = re.sub(r'[^-.0-9]', '', value_str)

    if cleaned_text and cleaned_text != '.' and cleaned_text.count('.') <= 1 and cleaned_text != '-':
        try:
            return float(cleaned_text) * multiplier
        except ValueError:
            return None
    return None


def scrape_yahoo_finance_cash_flow(ticker):
    """
    Scrapes Cash Flow statement data for a given ticker from Yahoo Finance.

    Args:
        ticker (str): The stock ticker symbol (e.g., 'AAPL').

    Returns:
        pd.DataFrame: A DataFrame containing the Cash Flow data, or an empty DataFrame if extraction fails.
    """
    soup = get_yahoo_finance_page_with_session(ticker, '/cash-flow/')
    if not soup:
        return pd.DataFrame()

    # Find the specific table container as identified during inspection
    table_container = soup.find('div', class_='tableContainer yf-yuwun0')
    if not table_container:
        print(f"Could not find the cash flow table (div.tableContainer.yf-yuwun0) for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from cash flow table for {ticker}...")

    # Extract column headers (fiscal periods)
    headers = []
    header_row_div = table_container.find('div', class_='tableHeader').find('div', class_='row yf-1yyu1pc')
    if header_row_div:
        # The first column is 'Breakdown', then periods
        period_columns = header_row_div.find_all('div', class_=re.compile(r'column yf-1yyu1pc'))[1:] # Skip 'Breakdown'
        headers = [div.get_text(strip=True) for div in period_columns]

    if not headers:
        print(f"Could not extract headers from the cash flow table for {ticker}.")
        return pd.DataFrame()

    # Add a 'Metric' column for the row labels
    column_names = ['Metric'] + headers

    extracted_data = []
    # Extract data rows
    for row_div in table_container.find('div', class_='tableBody').find_all('div', class_='row lv-0 yf-t22klz'):
        metric_name_div = row_div.find('div', class_='rowTitle yf-t22klz')
        if not metric_name_div:
            continue
        metric_name = metric_name_div.get_text(strip=True)

        values = [metric_name] # Start with the metric name
        # Get all value columns (skip the first sticky column which contains the metric name)
        value_columns = row_div.find_all('div', class_=re.compile(r'column yf-t22klz'))[1:]
        for val_div in value_columns:
            values.append(clean_value(val_div.get_text(strip=True)))

        # Ensure we have enough values for all columns, pad with None if necessary
        if len(values) < len(column_names):
            values.extend([None] * (len(column_names) - len(values)))

        extracted_data.append(values)

    df = pd.DataFrame(extracted_data, columns=column_names)
    df['Ticker'] = ticker
    return df

print("scrape_yahoo_finance_cash_flow function defined, including session handling and clean_value function.")



all_yahoo_finance_cash_flow_data = []

if unique_tickers:
    print(f"Starting to scrape Yahoo Finance Cash Flow for {len(unique_tickers)} unique tickers...")
    for i, ticker in enumerate(unique_tickers):
        print(f"Processing ticker {i+1}/{len(unique_tickers)}: {ticker}")
        cash_flow_df_for_ticker = scrape_yahoo_finance_cash_flow(ticker)
        if not cash_flow_df_for_ticker.empty:
            all_yahoo_finance_cash_flow_data.append(cash_flow_df_for_ticker)
        time.sleep(1) # Be polite between tickers

    # Consolidate all data into a final DataFrame
    if all_yahoo_finance_cash_flow_data:
        final_yahoo_finance_cash_flow_df = pd.concat(all_yahoo_finance_cash_flow_data, ignore_index=True)
        print("\n--- Consolidated Yahoo Finance Cash Flow Data ---")
        display(final_yahoo_finance_cash_flow_df.head())
        print(f"Total records across all tickers: {len(final_yahoo_finance_cash_flow_df)}")
        print(f"Columns: {final_yahoo_finance_cash_flow_df.columns.tolist()}")
    else:
        print("No Yahoo Finance cash flow data found for any ticker.")
        final_yahoo_finance_cash_flow_df = pd.DataFrame()
else:
    print("No unique tickers available to scrape Yahoo Finance Cash Flow.")
    final_yahoo_finance_cash_flow_df = pd.DataFrame()

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

# Assuming get_yahoo_finance_page_with_session and clean_value are already defined
# in the notebook's kernel state or copied from previous successful definitions.

def scrape_yahoo_finance_financials(ticker):
    """
    Scrapes Financial statement data (Income Statement) for a given ticker from Yahoo Finance.

    Args:
        ticker (str): The stock ticker symbol (e.g., 'AAPL').

    Returns:
        pd.DataFrame: A DataFrame containing the Financials data, or an empty DataFrame if extraction fails.
    """
    soup = get_yahoo_finance_page_with_session(ticker, '/financials/')
    if not soup:
        return pd.DataFrame()

    # Find the specific section container that holds the financial table
    financial_section = soup.find('section', class_='finContainer yf-yuwun0')

    if not financial_section:
        print(f"Could not find the financial section (section.finContainer.yf-yuwun0) for {ticker}.")
        return pd.DataFrame()

    # Within the financial section, locate the table container (often directly within it)
    table_container = financial_section.find('div', class_='tableContainer yf-yuwun0')
    if not table_container:
        print(f"Could not find the table container (div.tableContainer.yf-yuwun0) within the financial section for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from financial statements table for {ticker}...")

    # Extract column headers (fiscal periods)
    headers = []
    header_row_div = table_container.find('div', class_='tableHeader').find('div', class_='row yf-1yyu1pc')
    if header_row_div:
        # The first column is 'Breakdown', then periods
        period_columns = header_row_div.find_all('div', class_=re.compile(r'column yf-1yyu1pc'))[1:] # Skip 'Breakdown'
        headers = [div.get_text(strip=True) for div in period_columns]

    if not headers:
        print(f"Could not extract headers from the financial statements table for {ticker}.")
        return pd.DataFrame()

    # Add a 'Metric' column for the row labels
    column_names = ['Metric'] + headers

    extracted_data = []
    # Extract data rows from the tableBody
    for row_div in table_container.find('div', class_='tableBody').find_all('div', class_='row lv-0 yf-t22klz'):
        metric_name_div = row_div.find('div', class_='rowTitle yf-t22klz')
        if not metric_name_div:
            continue
        metric_name = metric_name_div.get_text(strip=True)

        values = [metric_name] # Start with the metric name
        # Get all value columns (skip the first sticky column which contains the metric name)
        value_columns = row_div.find_all('div', class_=re.compile(r'column yf-t22klz'))[1:]
        for val_div in value_columns:
            values.append(clean_value(val_div.get_text(strip=True)))

        # Ensure we have enough values for all columns, pad with None if necessary
        if len(values) < len(column_names):
            values.extend([None] * (len(column_names) - len(values)))

        extracted_data.append(values)

    df = pd.DataFrame(extracted_data, columns=column_names)
    df['Ticker'] = ticker
    return df

print("scrape_yahoo_finance_financials function defined, leveraging existing session handling and clean_value.")

# --- Apply scraper to all unique tickers ---
all_yahoo_finance_financials_data = []

# Ensure unique_tickers is available; if not, re-read from CSV
# global unique_tickers # This is already declared globally in other cells, but ensure it's accessible.
if 'unique_tickers' not in locals() or not unique_tickers:
    try:
        my_finviz_df_temp = pd.read_csv('/content/finviz_USA_stocks.csv')
        unique_tickers = my_finviz_df_temp['Ticker'].unique().tolist()
        print("unique_tickers loaded from CSV for Financials scraping.")
    except FileNotFoundError:
        print("finviz_USA_stocks.csv not found for Financials scraping. Please ensure Finviz scraping step was executed.")
        unique_tickers = []
    except KeyError:
        print("The 'Ticker' column was not found in finviz_USA_stocks.csv for Financials scraping.")
        unique_tickers = []

if unique_tickers:
    print(f"\nStarting to scrape Yahoo Finance Financials for {len(unique_tickers)} unique tickers...")
    for i, ticker in enumerate(unique_tickers):
        print(f"Processing ticker {i+1}/{len(unique_tickers)}: {ticker}")
        financials_df_for_ticker = scrape_yahoo_finance_financials(ticker)
        if not financials_df_for_ticker.empty:
            all_yahoo_finance_financials_data.append(financials_df_for_ticker)
        time.sleep(1) # Be polite between tickers

    # Consolidate all data into a final DataFrame
    if all_yahoo_finance_financials_data:
        final_yahoo_finance_financials_df = pd.concat(all_yahoo_finance_financials_data, ignore_index=True)
        print("\n--- Consolidated Yahoo Finance Financials Data ---")
        display(final_yahoo_finance_financials_df.head())
        print(f"Total records across all tickers: {len(final_yahoo_finance_financials_df)}")
        print(f"Columns: {final_yahoo_finance_financials_df.columns.tolist()}")
    else:
        print("No Yahoo Finance financials data found for any ticker.")
        final_yahoo_finance_financials_df = pd.DataFrame()
else:
    print("No unique tickers available to scrape Yahoo Finance Financials.")
    final_yahoo_finance_financials_df = pd.DataFrame()

"""# **Basic Ratios**"""

# @title
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def get_yahoo_finance_page_with_session(ticker='AAPL', url_path='/key-statistics'):
    """
    Attempts to fetch a Yahoo Finance page, handling the consent page using a persistent session.
    Returns a BeautifulSoup object of the page if successful, None otherwise.
    """
    session = requests.Session() # Initialize a session to persist cookies
    base_url = "https://finance.yahoo.com/quote/"
    target_url = f"{base_url}{ticker}{url_path}"

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1',
        'Sec-Fetch-Dest': 'document',
        'Sec-Fetch-Mode': 'navigate',
        'Sec-Fetch-Site': 'none',
        'Sec-Fetch-User': '?1'
    }

    print(f"Attempting to fetch {target_url} using session...")
    try:
        response_initial = session.get(target_url, headers=headers, allow_redirects=True)
        response_initial.raise_for_status()
        time.sleep(3)

        if "consent" in response_initial.url.lower() or "consent.cmp.oath.com" in response_initial.url.lower() or "consent.yahoo.com" in response_initial.url.lower() or "We need your consent" in response_initial.text:
            print(f"Detected Yahoo consent page at: {response_initial.url}")

            soup_consent = BeautifulSoup(response_initial.text, 'html.parser')
            consent_form = soup_consent.find('form', {'action': True, 'method': 'post'})
            if not consent_form:
                print("Could not find the consent form on the page. Cannot bypass.")
                return None

            form_data = {}
            for input_tag in consent_form.find_all('input', {'type': 'hidden'}):
                name = input_tag.get('name')
                value = input_tag.get('value')
                if name and value:
                    form_data[name] = value

            post_url = consent_form.get('action')
            if not post_url.startswith('http'):
                from urllib.parse import urljoin
                post_url = urljoin(response_initial.url, post_url)

            form_data['agree'] = 'agree'
            form_data['.submit'] = 'agree'
            headers['Referer'] = response_initial.url

            print(f"Submitting consent POST request to: {post_url} using session...")
            response_post = session.post(post_url, data=form_data, headers=headers, allow_redirects=True)
            response_post.raise_for_status()
            time.sleep(5)

            print(f"Consent POST successful. Final URL after consent: {response_post.url}")
            return BeautifulSoup(response_post.text, 'html.parser')
        else:
            print(f"Successfully accessed target page: {response_initial.url}")
            return BeautifulSoup(response_initial.text, 'html.parser')

    except requests.exceptions.RequestException as e:
        print(f"Error during Yahoo Finance access for {ticker}: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error occurred during Yahoo Finance access: {e}")
        return None

def extract_yf_quarterly_table_data(soup, ticker):
    """
    Extracts data from the 'yf-kbx2lo' table on Yahoo Finance Key Statistics page.

    Args:
        soup (BeautifulSoup): The BeautifulSoup object of the page.
        ticker (str): The stock ticker for which data is extracted.

    Returns:
        pd.DataFrame: A DataFrame containing the extracted quarterly data.
    """
    quarterly_table = soup.find('table', class_='yf-kbx2lo')
    if not quarterly_table:
        print(f"Could not find the quarterly table (table.yf-kbx2lo) for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from quarterly table for {ticker}...")

    # Extract column headers (dates/Current)
    headers = []
    header_row = quarterly_table.find('thead').find('tr')
    if header_row:
        # Skip the first empty <th>, then get text from remaining <th>s
        headers = [th.get_text(strip=True) for th in header_row.find_all('th')[1:]]

    if not headers:
        print(f"Could not extract headers from the quarterly table for {ticker}.")
        return pd.DataFrame()

    # Extract data rows
    extracted_data = []
    for row in quarterly_table.find('tbody').find_all('tr'):
        cols = row.find_all('td')
        if not cols: # Skip empty rows
            continue

        metric_name = cols[0].get_text(strip=True) # First column is the metric name
        values = [col.get_text(strip=True) for col in cols[1:]] # Remaining columns are values

        row_dict = {'Metric': metric_name, 'Ticker': ticker}
        for i, header in enumerate(headers):
            row_dict[header] = values[i] if i < len(values) else None
        extracted_data.append(row_dict)

    df = pd.DataFrame(extracted_data)
    return df

# --- Main execution ---
sample_ticker = 'AAPL'
soup_obj = get_yahoo_finance_page_with_session(ticker=sample_ticker, url_path='/key-statistics')

if soup_obj:
    quarterly_df = extract_yf_quarterly_table_data(soup_obj, sample_ticker)
    if not quarterly_df.empty:
        print("\n--- Extracted Quarterly Data ---")
        display(quarterly_df.head(10))
    else:
        print("No quarterly data extracted.")
else:
    print("Failed to get BeautifulSoup object for Yahoo Finance Key Statistics page.")

"""# **Total Assests**"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import re

def scrape_yahoo_finance_balance_sheet(ticker):
    """
    Scrapes Balance Sheet data for a given ticker from Yahoo Finance.

    Args:
        ticker (str): The stock ticker symbol (e.g., 'AAPL').

    Returns:
        pd.DataFrame: A DataFrame containing the Balance Sheet data, or an empty DataFrame if extraction fails.
    """
    soup = get_yahoo_finance_page_with_session(ticker, '/balance-sheet/')
    if not soup:
        return pd.DataFrame()

    # Find the specific table container as identified during inspection
    table_container = soup.find('div', class_='tableContainer yf-yuwun0')
    if not table_container:
        print(f"Could not find the balance sheet table (div.tableContainer.yf-yuwun0) for {ticker}.")
        return pd.DataFrame()

    print(f"Extracting data from balance sheet table for {ticker}...")

    # Extract column headers (fiscal periods)
    headers = []
    header_row_div = table_container.find('div', class_='tableHeader').find('div', class_='row yf-1yyu1pc')
    if header_row_div:
        # The first column is 'Breakdown', then periods
        period_columns = header_row_div.find_all('div', class_=re.compile(r'column yf-1yyu1pc'))[1:] # Skip 'Breakdown'
        headers = [div.get_text(strip=True) for div in period_columns]

    if not headers:
        print(f"Could not extract headers from the balance sheet table for {ticker}.")
        return pd.DataFrame()

    # Add a 'Metric' column for the row labels
    column_names = ['Metric'] + headers

    extracted_data = []
    # Extract data rows
    for row_div in table_container.find('div', class_='tableBody').find_all('div', class_='row lv-0 yf-t22klz'):
        metric_name_div = row_div.find('div', class_='rowTitle yf-t22klz')
        if not metric_name_div:
            continue
        metric_name = metric_name_div.get_text(strip=True)

        values = [metric_name] # Start with the metric name
        # Get all value columns (skip the first sticky column which contains the metric name)
        value_columns = row_div.find_all('div', class_=re.compile(r'column yf-t22klz'))[1:]
        for val_div in value_columns:
            values.append(clean_value(val_div.get_text(strip=True)))

        # Ensure we have enough values for all columns, pad with None if necessary
        if len(values) < len(column_names):
            values.extend([None] * (len(column_names) - len(values)))

        extracted_data.append(values)

    df = pd.DataFrame(extracted_data, columns=column_names)
    df['Ticker'] = ticker
    return df

print("scrape_yahoo_finance_balance_sheet function defined, leveraging existing session handling and clean_value.")

all_yahoo_finance_balance_sheet_data = []

if unique_tickers:
    print(f"Starting to scrape Yahoo Finance Balance Sheet for {len(unique_tickers)} unique tickers...")
    for i, ticker in enumerate(unique_tickers):
        print(f"Processing ticker {i+1}/{len(unique_tickers)}: {ticker}")
        balance_sheet_df_for_ticker = scrape_yahoo_finance_balance_sheet(ticker)
        if not balance_sheet_df_for_ticker.empty:
            all_yahoo_finance_balance_sheet_data.append(balance_sheet_df_for_ticker)
        time.sleep(1) # Be polite between tickers

    # Consolidate all data into a final DataFrame
    if all_yahoo_finance_balance_sheet_data:
        final_yahoo_finance_balance_sheet_df = pd.concat(all_yahoo_finance_balance_sheet_data, ignore_index=True)
        print("\n--- Consolidated Yahoo Finance Balance Sheet Data ---")
        display(final_yahoo_finance_balance_sheet_df.head())
        print(f"Total records across all tickers: {len(final_yahoo_finance_balance_sheet_df)}")
        print(f"Columns: {final_yahoo_finance_balance_sheet_df.columns.tolist()}")
    else:
        print("No Yahoo Finance balance sheet data found for any ticker.")
        final_yahoo_finance_balance_sheet_df = pd.DataFrame()
else:
    print("No unique tickers available to scrape Yahoo Finance Balance Sheet.")
    final_yahoo_finance_balance_sheet_df = pd.DataFrame()
